### PR TITLE
Always log in through the client

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Currently, when accessing a protected resource in the browser, node-solid-server would provide you with its own UI for selecting an IDP and logging in. This would only create a server session, but not a client login: regular browser requests would work, but AJAX requests would fail. You would need to log in a second time with solid-auth-client to make Databrowser and others work.

To address that, this pull request:
- removes the node-solid-server IDP selection UI
- replaces it with a solid-auth-client login (fixing #747)

Not only does this provide an identical user experience for server- and client-initiated logins, it also synchronizes client-side and server-side login (to the extent possible; more work to be done in #736).

### CODE REVIEW

**Comment by justinwb** [comment]
This seems to be working well. The only problem that I ran into was the symlinks not getting created correctly when I did the install, which I did in the inrupt dev environment by running 'npm install -g git://github.com/solid/node-solid-server.git#feature/client-login'. Once I created them by hand, everything worked well.

**Comment by RubenVerborgh** [comment]
Thanks for testing. Is the location of the module different in a global install? It might be at ../solid-auth-client instead of ./node_modules/solid-auth-client .

If so, I need to account for this.

**Comment by kjetilk** [comment]
Sounds good! Seems like we can get this into 4.1.0 indeed, if we can get that final issue settled.

**Comment by justinwb** [comment]
It's still at ./node_modules/solid-auth-client even in the global install (absolute path of /usr/lib/node_modules/solid-server/node_modules/solid-auth-client on this ubuntu 16.04 install). I did some very quick digging and i think it may actually be a problem with npm's support of symlinks. Check out https://github.com/npm/npm/issues/13050

**Pull request merged**
