### PR TITLE
:ant: Reuse ldp

### PR DESCRIPTION
**Pull request by ludwigschubi**

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
@ludwigschubi - what is `:ant:`, out of curiosity?

**Comment by ludwigschubi** [comment]
It's this :ant: emoji or emoticon I am not sure of the actual name, I just thought of adding it because this PR is just a tiny change 😄

**Comment by dmitrizagidulin** [comment]
@ludwigschubi hahahah, k :)

**Comment by Ryuno-Ki** [comment]
Some people [were all raged about ants](https://curlicuecal.tumblr.com/post/175362924100/an-entomologist-rates-ant-emojis) a couple of years ago ;-)

**Pull request merged**
