### PR TITLE
Switch from node-mime to mime-types lib

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Researching a fix for issue #413 (fixing support for the .jsonld file extension) pointed to the limitation of the `node-mime` lib we're using. This PR proposes to switch to the [`mime-types`](https://github.com/jshttp/mime-types) lib instead (which, incidentally, already has support for `jsonld`). Benefits of switching:

- It's based on https://github.com/jshttp/mime-db, which draws from IANA, Apache and Nginx registries
- It looks better maintained (take a look at the discussion in issue 108 at https://github.com/broofa/node-mime/issues/ for example)
- The API is the same (aside from not having a `default_type`, which is addressed in the PR)

### CODE REVIEW

**Comment by nicola** [comment]
LGTM

**Comment by csarven** [comment]
```
  solid:get error translating: /dokieli/inbox/abcdef false -> text/turtle -- 500 Error trying to parse <https://localhost:8443> as false:
Error: Don't know how to parse false yet:
Error: Don't know how to parse false yet
    at Object.parse (/var/www/node-solid-server.original/node_modules/rdflib/src/parse.js:58:13)
    at parse (/var/www/node-solid-server.original/lib/utils.js:104:10)
    at ReadStream.<anonymous> (/var/www/node-solid-server.original/lib/utils.js:144:7)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +0ms
  solid:server Error page because of Error translating between RDF formats +0ms
```

abcdef:
```
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix oa: <http://www.w3.org/ns/oa#> . 
@prefix schema: <https://schema.org/> .
<> a as:Dislike
    ; as:object <https://localhost:8443/dokieli/index.local.html#researchers>
    ; as:updated "2016-08-08T17:26:43.768Z"^^xsd:dateTime
    ; as:actor <http://csarven.ca/#i>
    ; schema:license <https://creativecommons.org/licenses/by/4.0/>
    .
```

**Comment by csarven** [comment]
Probably due this:
`Accept:text/turtle, application/ld+json, application/xhtml+xml, text/html`
`Content-Type:text/html; charset=utf-8`

**Comment by dmitrizagidulin** [comment]
@csarven should be fixed in PR 431

**Comment by csarven** [comment]
Note that `.nt` gets used as `text/turtle` because N-Triples is not listed at http://www.iana.org/assignments/media-types/media-types.xhtml - and so mime-types/mimes-db lib are not aware of it. N-Triple is intended to have `application/n-triples` mime type. The same parser (N3 probably) that's used for Turtle should be fine. You could manually at that in or ping upstream.

:santa:

**Pull request merged**
