### PR TITLE
Fix Local Windows Development

### PR DESCRIPTION
**Pull request by mohamedmansour**
When it was reading from disk index.html, it added the wrong
slash, use url.resolve to fix this.

### CODE REVIEW

**Comment by mohamedmansour** [comment]
@dmitrizagidulin this fixes the ACL to match, tested on windows 10

**Comment by dmitrizagidulin** [comment]
:+1: looks reasonable.

**Comment by mohamedmansour** [comment]
@RubenVerborgh  how would you otherwise do this when `reqPath` is `\index.html` Manual string manipulation.  This is how express handles it since it is coming from the windows filepath. Are you certain URL.resolve is bad for security? We always use it to make sure URLs are joined correctly is cross plat.

**Comment by mohamedmansour** [comment]
@RubenVerborgh  maybe the way we are reading the ACL? `<./index.html>` Node resolves it as `\index.html` in Windows? Let me understand how ACLs are being read now.

**Comment by RubenVerborgh** [comment]
> maybe the way we are reading the ACL? `<./index.html>` Node resolves it as `\index.html` in Windows?

It's not Node resolving this, it must be our code instruction Node to do so. But ACLs should be resolved as URLs, not as files. So there is something wrong with our ACL resolver code if filename conventions (like backslashes) are creeping in.

**Comment by kjetilk** [comment]
@RubenVerborgh Perhaps raise a separate issue about ACL resolving?

**Comment by RubenVerborgh** [comment]
Yes. @mohamedmansour Could you come up with an exact description of what you encounter under what circumstances? I.e., a bug report? Then we can investigate if this PR is the correct fix for that bug.

**Pull request closed without merging**
