### PR TITLE
Communicate an originsAllowed from config

### PR DESCRIPTION
**Pull request by kjetilk**
This should communicate an `originsAllowed` option all the way from the default config and up to the ACLchecker, which again passes it to the `PermissionSet`. Also adds some debugging.

Obviously, the actual trusted origin has to change once we have registered and agreed on domain for it.

We should perhaps have an integration test, but I figured I'd let you poke at it first. :-)

### CODE REVIEW

**Comment by kjetilk** [comment]
Bug description is in https://github.com/solid/solid-permissions/issues/26

**Comment by kjetilk** [comment]
I'm thinking perhaps that some of the strange behaviour that I've seen is actually caused by wrong configs, i.e. #776 .

**Comment by RubenVerborgh** [comment]
Can you look at merging #776 then? I'll rebase.

**Comment by RubenVerborgh** [comment]
#776 has been merged, you might want/need to rebase.

**Pull request merged**
