### PR TITLE
Remove unused n3 dependency

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Removing unused n3 dependency -- N3 parsing is taken care of by rdflib etc.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Tagging @nicola / @deiu / @dan-f for review.

**Comment by deiu** [comment]
We *could* drop it for now, but I have a feeling Tim wants to stream N3 patches through websockets soon.

**Comment by dan-f** [comment]
:+1: for deleting a commented out file and unused dependency. If we want to add that n3 library in the future and use it, I don't see how this would at all get in the way of that.

**Comment by dmitrizagidulin** [comment]
These updates are now part of PR https://github.com/solid/node-solid-server/pull/456. (Closing this one).

**Pull request closed without merging**
