### PR TITLE
Directly serve mashlib's data browser bundle

### PR DESCRIPTION
**Pull request by Vinnl**
This way, node-solid-server no longer needs to carry its own copy
of the data browser, and mashlib can include additional assets,
such as stylesheets.

Should only be merged in tandem with https://github.com/solid/mashlib/pull/27.

### CODE REVIEW

**Comment by Vinnl** [comment]
(Ah, there's failing tests - will work on that, sorry.)

**Comment by Vinnl** [comment]
Right, so the two tests that fail in CI only fail because it doesn't include a version of mashlib with https://github.com/solid/mashlib/pull/27 merged. That said, there were a few other tests failing due to the `index.html` being served at the root; I've turned that off now and all tests succeed locally.

**Comment by Vinnl** [comment]
Cool, I just incorporated v0.8.0 of mashlib, that includes the changes in https://github.com/solid/mashlib/pull/27, and rebased it on `master`. Ready to merge as far as I'm concerned.

**Comment by TallTed** [comment]
Fixing conflicts will likely speed the merge...

**Comment by Vinnl** [comment]
Sorry @TallTed, I hadn't received a message that conflicts were introduced. Rebased on `master` again.

**Pull request merged**
