### PR TITLE
Adding fullscreen support for login on iOS

### PR DESCRIPTION
**Pull request by emiliocortina**
#1182

### CODE REVIEW

**Comment by emiliocortina** [comment]
@jaxoncreed Sorry for taking so long to answer. 
It also seems to happen when I run the tests locally. I checked the tests failing in travis and locally and they appear to be the same.
The thing is that I ran the tests against the repository before the changes I made and it still shows the same failing tests.
Screenshot 2019-05-06 at 12 43 54

**Comment by jaxoncreed** [comment]
Oh that's interesting. I'm seeing the same thing. I'll look into that and get back to you.

**Comment by jaxoncreed** [comment]
Okay, @emiliocortina you're code's all good. Looks like one of the sites we have deployed to help us with tests is done.

I've pinged @RubenVerborgh to help us out with that, so once it's back up I'll run the tests.

**Comment by emiliocortina** [comment]
@jaxoncreed Great! Thanks for your help.

**Pull request merged**
