### PR TITLE
Set rejectUnauthorized on solid-test

### PR DESCRIPTION
**Pull request by RubenVerborgh**

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
@dmitrizagidulin Another possibility is to rename the option into  `--no-reject-unauthorized`.

**Comment by dmitrizagidulin** [comment]
Renaming it to `--no-reject-unauthorized` seems reasonable. (Denotes that rejecting is the normal state, and that not doing it is the exception.)

**Comment by RubenVerborgh** [comment]
@dmitrizagidulin Thanks, updated.

**Comment by RubenVerborgh** [comment]
@dmitrizagidulin …and without Warp this time.

**Comment by dmitrizagidulin** [comment]
Hehe, thanks

**Pull request merged**
