### PR TITLE
Merge dev branch?

### PR DESCRIPTION
**Pull request by michielbdejong**
@jaxoncreed @angelo-v should we merge dev into master?

### CODE REVIEW

**Comment by linonetwo** [comment]
I really need it...

**Comment by kjetilk** [comment]
FWIW, when I developed, we stopped using a dev branch, had feature branches of course, but released off `master` and merged onto a `released` branch, which then behaves like the current `master`.

**Comment by linonetwo** [comment]
I'm making an electron app that start a local server, I really need a new npm release!

**Comment by mikeadams1** [comment]
> we stopped using a dev branch, had feature branches of course, but released off `master` and merged onto a `released` branch, which then behaves like the current `master`.

I am confused, so are there numerous NSS repos that are not visible to the general public and those are whats being worked on? I did not see any updates on the alleged NSS master? and not sure what /tree/dev is, can you help me understand that?

**Comment by kjetilk** [comment]
> > we stopped using a dev branch, had feature branches of course, but released off `master` and merged onto a `released` branch, which then behaves like the current `master`.
> 
> I am confused, so are there numerous NSS repos that are not visible to the general public and those are whats being worked on? I did not see any updates on the alleged NSS master? and not sure what /tree/dev is, can you help me understand that?

No, there's just one repo, but the nature of git is so that you can branch off any way and anywhere, it is completely decentralised. Typically, a developer will work on their own branch, and then submit a Pull Request to some more authoritative branch, so projects prefer to use the default `master` branch for that, some prefer a `dev` branch, some have more complex arrangements. If you look at the "Insights" tab, you find a lot of information about this, for example, all the branches that have been pushed way back to github (which is kind of a central hub in the decentralised git), can be seen here: https://github.com/solid/node-solid-server/network

**Pull request merged**
