### PR TITLE
Fixes for WebID delegation (to be detailed)

### PR DESCRIPTION
**Pull request by smalinin**
Recreated PR https://github.com/solid/node-solid-server/pull/701 with fresh fork

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Note, the branch has been renamed into feature/webid-delegation, since this will not be part of v4.1.

**Comment by RubenVerborgh** [comment]
Note: the commit history might be off on this one, since I think this PR merges develop into the diverged branch feature/webid-delegation (but has no explicit merge commit).

**Comment by melvincarvalho** [comment]
I'll note the branch `dz fix delegation` which might contain some useful pointers

https://github.com/solid/node-solid-server/tree/dz_fix_delegation

**Comment by jaxoncreed** [comment]
Closing due to inactivity

**Pull request closed without merging**
