### PR TITLE
Expose the user's permissions through a header

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Implements #246 with `WAC-Allowed: user="read write append",public="read"`.

### CODE REVIEW

**Comment by csarven** [comment]
Good stuff!

Would "WAC-Mode" be preferable just to keep it closer to *nix's *mode bits*?

**Comment by RubenVerborgh** [comment]
@csarven The header name was chosen in a discussion with @timbl and @dmitrizagidulin yesterday (see #246). I don't mind the naming either way (although I still think "WAC" is cryptic).

**Comment by dmitrizagidulin** [comment]
I just realized we want to do `WAC-Allow`, minus the *ed* on the end. (To match the HTTP `Allow:` header). Sorry bout that :)

**Comment by RubenVerborgh** [comment]
Which of these would you prefer? I don't mind either way; I was following what @dmitrizagidulin wrote down of our discussion in #246.

**Comment by csarven** [comment]
To stick close to convention (like in Web Linking for relation types), probably best to use space as a delimiter. Plus, it is easier to read.

**Comment by RubenVerborgh** [comment]
Makes sense! Are the quotes needed?

**Comment by csarven** [comment]
I think the quotes might make it easier for consumers to tokenise. It can also help to escape characters or have specialised modes or something in the future.

**Comment by RubenVerborgh** [comment]
Okay, mandatory quotes it is.

**Comment by RubenVerborgh** [comment]
250e5132f79ebe5c0d2d84b21ae7de78a7cf76bf brings spaces.

**Comment by RubenVerborgh** [comment]
Currently on hold because of #552.

**Comment by RubenVerborgh** [comment]
#552 has been merged, so this one is ready for review and merge.

**Pull request merged**
