### PR TITLE
Merge master into v5

### PR DESCRIPTION
**Pull request by kjetilk**
I think we should merge master into v5.0.0, any reason why we might not?

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
@kjetilk - it's generally better to _rebase_ on master, rather than merge master in :)

**Comment by kjetilk** [comment]
but, but, it is scary... :-) OK, so, if I go

```
kjetil@robin:~/dev/solid/node-solid-server (integrate-acl-check)$ git checkout release/v5.0.0 
Switched to branch 'release/v5.0.0'
Your branch is up-to-date with 'origin/release/v5.0.0'.
kjetil@robin:~/dev/solid/node-solid-server (release/v5.0.0)$ git rebase master
```
...fix the perennial `package-lock.json` conflict, and then push, I should be fine?

**Comment by dmitrizagidulin** [comment]
Hahaha but `rebase` is your friend! (or can be, with some practice.)

And yes - that should work!

**Comment by dmitrizagidulin** [comment]
Oh wait, one more detail - after you rebase and fix package-lock, the subsequent push needs to be a `push -f`

**Comment by dmitrizagidulin** [comment]
so:

```
git rebase master
# ... fix package
git push origin release/v5.0.0 -f
```

**Comment by kjetilk** [comment]
Arrrggh! I did a `git pull`, and thought that would give me all at origin, but that didn't happen, so I had to merge the rest, and now I'm terrified again...

**Comment by kjetilk** [comment]
OK, I think the rebase was successful

**Pull request merged**
