### PR TITLE
Set up SonarJS static analysis

### PR DESCRIPTION
**Pull request by RubenVerborgh**

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Making it run is just the package and Travis changes. Stopping it from complaining is the other changes.

**Comment by kjetilk** [comment]
OK, I would have preferred smaller, more atomic commits, but I can live with this. :-)

**Comment by RubenVerborgh** [comment]
Yeah, my rule is that the build should work on each individual commit, so couldn't split up this one :-)

**Comment by kjetilk** [comment]
Oh, OK! 

Actually, we should talk about that. My policy is just the build should succeed when I push, so I tend to have lots of commits between each push.

**Comment by RubenVerborgh** [comment]
Indeed, we should have a document about policies and procedures.

**Comment by kjetilk** [comment]
Yeah, lets discuss on gitter

**Comment by RubenVerborgh** [comment]
I had to drop Sonar because it has issues with symlinks. We were using the wrong version apparently: https://github.com/SonarSource/SonarJS/issues/1057

**Pull request merged**
