### PR TITLE
Merge master into v5 branch

### PR DESCRIPTION
**Pull request by kjetilk**
It is a good time to do it, since I've just released 4.4.1.

### CODE REVIEW

**Comment by kjetilk** [comment]
Hmpf, I edited many of the files with the Web editor to resolve conflicts, but they weren't saved for some reason.

I think most of the conflicts in the JS files are in things you've worked with @megoth , so perhaps you can resolve and merge?

**Comment by megoth** [comment]
> Hmpf, I edited many of the files with the Web editor to resolve conflicts, but they weren't saved for some reason.
> 
> I think most of the conflicts in the JS files are in things you've worked with @megoth , so perhaps you can resolve and merge?

I'll give it a go ^_^

**Comment by kjetilk** [comment]
@joachimvh : @megoth and I had a look at it, and we found ourselves to be a bit uncertain about your Windows-related commits. Also, we don't have Windows to test. We did fix the rest of the files, but apparently, you can't commit things that are just half-merged, so that doesn't show.

Could you please look to merge this, @joachimvh ?

**Comment by joachimvh** [comment]
I'll have a look

**Comment by kjetilk** [comment]
Thanks a lot!

**Pull request merged**
