### PR TITLE
Update SSL Certificate Naming Convention (Issue 876)

### PR DESCRIPTION
**Pull request by steven-tomlinson**
This change addresses Issue #876 'consider renaming localhost.key to privkey.pem'

Edited README.MD
Changed test environment instructions for generating self-signed SSL certificate to explcitly create a PEM certificate.
Added tip to eliminate browser warning.

'./config.json-default' updated
Will now use privkey.pem instead of 'localhost.key' as default SSL private key name in a test environment.

Edited EXAMPLES.MD to reflect preference for new SSL naming convention.

'./config.json-default' updated
Will now use fullchain.pem instead of 'localhost.cert' as default SSL Certificate Name in a test environment.

'./Dockerfile' updated
Will now use fullchain.pem instead of 'localhost.cert' as default SSL Certificate File Name  when generating Certificate Request.

'./Dockerfile' updated
Will now use privkey.pem instead of 'localhost.key' as default SSL Key File Name when generating Certificate Request.

This contribution to Solid is governed by the MIT License.

### CODE REVIEW

**Comment by steven-tomlinson** [comment]
I added the additional change to the Dockerfile, as suggested by @melvincarvalho in the original issue discussion ( https://github.com/solid/node-solid-server/issues/876 )

**Comment by melvincarvalho** [comment]
@steven-tomlinson looks good to me, given that docker will do this every time.

I thin kthe snyk thing is failing on more than one issue.  I dont get any details when clicking on it : 

> Unable to display this organisation

> The organisation does not exist, or you do not have permissions to access it.

@kjetilk ?

**Comment by steven-tomlinson** [comment]
@melvincarvalho based on Ruben's comments, I think this is ready for review. Is there anything else I should do to get this completed and closed?

**Comment by kjetilk** [comment]
Am I right in assuming that this is something that would only influence new installs? In which case, we can do it in on the 4.x branch.

**Comment by RubenVerborgh** [comment]
Yes.

**Comment by kjetilk** [comment]
OK, good! I've rebased it on `develop`.

**Comment by melvincarvalho** [comment]
Looks great!

Can I check these 2?

> $ openssl req -outform PEM -keyform PEM -new -x509 -sha256 -newkey rsa:2048 -nodes -keyout ../privkey.pem -days 365 -out ../fullchain.pem

is the same as ?

> $ openssl genrsa 2048 > ../localhost.key

> $ openssl req -new -x509 -nodes -sha256 -days 3650 -key ../localhost.key -subj '/CN=*.localhost' > ../localhost.cert

And should the days be 3650 to be consistent?  Actually I normally go with 36500 to give self signed certs no expiry.

**Comment by steven-tomlinson** [comment]
@melvincarvalho 
this line: "$ openssl req -outform PEM -keyform PEM -new -x509 -sha256 -newkey rsa:2048 -nodes -keyout ../privkey.pem -days 365 -out ../fullchain.pem"

will create the key and cert file in one line and put them in the directory above the directory where the command is executed.
The only difference between it and the two commands you quoted are the number of expiration days for the certificate.

Once the command is executed the user will be prompted for the Subject (CN, OU, etc.).

**Comment by steven-tomlinson** [comment]
@kjetilk should I rebase my branch on 'develop' instead of 'master" as well before initiating a pull request?

**Comment by kjetilk** [comment]
> @kjetilk should I rebase my branch on 'develop' instead of 'master" as well before initiating a pull request?

Normally, yes, but I did it for you this time! :-) 

We need to reconsider which branch is our default, I think.

**Pull request merged**
