### PR TITLE
refactor: replace colors with colorette

### PR DESCRIPTION
**Pull request by jorgebucaran**
👋 Hello maintainers.

## Summary

This PR replaces colors with [colorette](https://github.com/jorgebucaran/colorette). Disclaimer: I'm the author of colorette. This is a refactor change and does not intend to introduce breaking changes. Please let me know if this looks good or not and if you'd like me to make any changes.

Colorette is both lighter and faster than the colors packages. It's also "safe" by default, it doesn't mutate the string prototype. Terminal color support is autodetected, so our console output will not contain unreadable symbols if the target terminal does not support color.

Tests and coverage are at 100%.

## Size Comparison

| Package | Size |
|-|-|
| `colors` |[install size](https://packagephobia.now.sh/result?p=colors)|
| `colorette` | [install size](https://packagephobia.now.sh/result?p=colorette)|

## Runtime Performance

All tests run on a 2.4GHz Intel Core i7 CPU with 16 GB memory. Complete benchmark results [here](https://github.com/jorgebucaran/colorette#benchmark-results) and implementation [here](https://github.com/jorgebucaran/colorette/tree/master/bench).

```
# Using Styles
colors × 64,999 ops/sec
> colorette × 709,733 ops/sec

# Combining Styles
colors × 246,004 ops/sec
> colorette × 2,049,555 ops/sec

# Nesting Styles
colors × 144,403 ops/sec
> colorette × 389,825 ops/sec
```

### CODE REVIEW

**Comment by kjetilk** [comment]
Looks cool! Could you please make sure Travis passes by updating the locks?

**Comment by jorgebucaran** [comment]
@kjetilk Thank you. Yes, done.

**Comment by RubenVerborgh** [comment]
@kjetilk Needs rebase.

**Comment by jorgebucaran** [comment]
> @kjetilk And, BTW, we had some questions about whether we should have a CLA, and we don't know, but we'd just figured we'd ask if you're OK with the MIT license?

I'm perfectly OK with the MIT license.


@RubenVerborgh Sure. Rebase completed.

**Comment by RubenVerborgh** [comment]
@jorgebucaran There still appear to be some conflicts though.

**Comment by jorgebucaran** [comment]
@RubenVerborgh You are right. Sorry, I don't know how to fix the conflict, so I've created a new identical PR here. https://github.com/solid/node-solid-server/pull/812

**Pull request closed without merging**
