### PR TITLE
Cache node_modules in Travis

### PR DESCRIPTION
**Pull request by rubensworks**
This makes Travis builds slightly faster.

### CODE REVIEW

**Comment by rubensworks** [comment]
Ah, TIL `npm ci` deletes `node_modules`.

In any case, it looks like `npm install` without changes dependencies takes about 7,5 seconds, while `npm ci` takes 30 seconds.

So `npm install` is definitely faster if `node_modules` can be cached. So do we want to transition to that instead? (`npm ci` is of course better in the sense that it starts from a clean environment)

**Comment by RubenVerborgh** [comment]
I strongly suggest `npm ci` for consistency reasons. It's slower, but doesn't make mistakes.

**Comment by rubensworks** [comment]
Sure, I can live with that :-)

In any case, installation is not the main bottleneck in Travis builds.

**Comment by RubenVerborgh** [comment]
@rubensworks Apparently we can cache npm though: https://docs.travis-ci.com/user/caching/#npm-cache

**Comment by rubensworks** [comment]
Apparently GitHub doesn't allow you to re-open PRs after force-pushing to the branch. Created #971 instead.

**Pull request closed without merging**
