### PR TITLE
Fix single-user signup redirect

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Addresses issue #498.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
@pmcb55 - can you try out this branch, confirm it fixes the issue?

**Comment by pmcb55** [comment]
I just applied this fix (hack?) and confirmed that it now renders the 'Create Account' form rather than failed with 'Too many redirects'.

**Comment by dmitrizagidulin** [comment]
Still need to address "access denied on /signup.html" issue.

**Comment by reinvented** [comment]
_With apologies for my naiveté here._

To test this branch, I uninstalled solid-server (`npm uninstall solid-server`) and then installed this branch:

```
npm install --save https://github.com/solid/node-solid-server/tarball/fix-single-user-signup
```

I started solid-server:

```
# solid start -v
  solid:settings Suffix Acl: .acl +0ms
  solid:settings Suffix Meta: .meta +3ms
  solid:settings Filesystem Root: /var/www/solid/ +1ms
  solid:settings Allow WebID authentication: true +0ms
  solid:settings Live-updates: true +0ms
  solid:settings Identity Provider: false +0ms
  solid:settings Default file browser app: https://linkeddata.github.io/warp/#/list/ +0ms
  solid:settings Suppress default data browser app: undefined +0ms
  solid:settings Default data browser app file path: undefined +0ms
  solid:settings XSS/CORS Proxy listening at //proxy?uri={uri} +5ms
  solid:settings Base URL (--mount): / +5ms
  solid:settings SSL Private Key path: /etc/letsencrypt/live/peter.rukavina.net/privkey.pem +1ms
  solid:settings SSL Certificate path: /etc/letsencrypt/live/peter.rukavina.net/fullchain.pem +0ms
Solid server (solid v3.5.0) running on https://localhost:8443/
Press <ctrl>+c to stop
```

Visiting https://peter.rukavina.net:8443/ prompts for a certificate; I click Cancel, which redirects me to https://peter.rukavina.net:8443/signup.html, which results in the error **Access to https://peter.rukavina.net:8443/signup.html requires authorization**  and the following in the log:

```
  solid:accounts (single user mode) Redirecting to account creation +5m
  solid:authentication No client certificate found in the request. Did the user click on a cert? +96ms
  solid:ACL Can an agent Read https://peter.rukavina.net:8443/signup.html? +3ms
  solid:ACL Check if acl exist: https://peter.rukavina.net:8443/signup.html.acl +0ms
  solid:ACL Error: HTTPError: Can't read file +3ms
  solid:ACL Check if acl exist: https://peter.rukavina.net:8443/.acl +0ms
  solid:ACL Error: HTTPError: Can't read file +0ms
  solid:ACL No ACL resource found - access not allowed +1ms
  solid:ACL Error: No Access Control Policy found +0ms
  solid:ACL Authentication required +0ms
  solid:server Error page because of Access to https://peter.rukavina.net:8443/signup.html requires authorization +0ms
```

My config.json is as follows:

```
{
  "root": "/var/www/solid",
  "port": "8443",
  "serverUri": "https://peter.rukavina.net:8443",
  "webid": true,
  "mount": "/",
  "sslKey": "/etc/letsencrypt/live/peter.rukavina.net/privkey.pem",
  "sslCert": "/etc/letsencrypt/live/peter.rukavina.net/fullchain.pem",
  "idp": false,
  "proxy": "/proxy"
}
```

**Comment by dmitrizagidulin** [comment]
@reinvented no problem, thanks for trying it out!
Things to try: 

- Make sure to delete the contents of the root data dir, `/var/www/solid/`. (The signup code in single-user mode works only if there's no account already created, even partially.)
- Make sure that tarball has the latest version of this branch (like, make sure [line 129](https://github.com/solid/node-solid-server/pull/499/files#diff-a04a08c44968df7c80e57baa9b33e970R129) is present, etc)


 Do you have Git installed on that machine? 

https://github.com/solid/node-solid-server.git

**Comment by reinvented** [comment]
I can confirm that, after doing what @dmitrizagidulin suggested, this branch solves the redirect issue for me.

There's still an issue with certificates subsequently generated not being properly ingested by Firefox, but that's a separate issue.

**Comment by dmitrizagidulin** [comment]
@reinvented thanks!

**Comment by tomasklapka** [comment]
I have the same issue, configuration and output as described here https://github.com/solid/node-solid-server/pull/499#issuecomment-294932974 by @reinvented 
Data dir is empty and i've checked I use the version from this commit. Getting access denied.

If I copy signup.html.acl into the data dir, I get this error: 
```
  solid:ACL Check if acl exist: https://localhost:8443/signup.html.acl +1ms
  solid:ACL Read access permitted to  +16ms
  solid:ACL ACL policy found +0ms
  solid:get /signup.html on localhost +1ms
  solid:get GET -- Error: 404 Can't find file requested: /data2/space/solid-local/data/signup.html +3ms
  solid:server Error page because of Can't find file requested: /data2/space/solid-local/data/signup.html +0ms
```
If I copy signup.html into the data dir as well, I finally get to the page.

**Comment by dmitrizagidulin** [comment]
@tomasklapka thanks for the heads up. I'll investigate.

**Comment by tomasklapka** [comment]
If I install solid globally (-g) it does not find static files. If I install it through ```git clone``` and ```git branch fix-single-user-signup``` it works fine. I guess it is because there are relative paths used. 
To make globally installed solid work I successfuly used path.join and _dirname:
```
          const path = require('path');
          router.use('/signup.html', express.static(path.join(__dirname,'/static/signup.html')))
          router.use('/signup.html.acl', express.static(path.join(__dirname,'/static/signup.html.acl')))
```

Now when it works for me, I've noticed that there is no webid stored in my browser so any created access gets lost when browser is restarted. Should I file this one as a separate issue?

The missing spkac param message is suspicious to me:
```
  solid:accounts (single user mode) Redirecting to account creation +21s
  solid:accounts Missing spkac param, not generating cert during account creation +25s
  solid:accounts Creating account folder for https://localhost:8443/profile/card#me at /data2/space/node-solid-server/data/ +0ms
  solid:accounts Account storage resources created +48ms
  solid:accounts Sending Welcome email +1ms
  solid:accounts Adding a new certificate for https://localhost:8443/profile/card#me +36s
  solid:handlers PUT -- Wrote data to: /data2/space/node-solid-server/data/profile/card +416ms
  solid:authentication User: https://localhost:8443/profile/card#me +22s
```

**Pull request merged**
