### PR TITLE
Remove github dependencies

### PR DESCRIPTION
**Pull request by justinwb**
Removing all github package dependencies. Removed reference to databox.me from README. Added myself to list at bottom.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
> package-lock.json has been changed from https to http

We might want to set them back. Not too important, but npm will insist on changing them at some point in the future.

**Comment by RubenVerborgh** [comment]
Perfect, with this last commit, the only `@trust` dependencies remaining are to stable packages.

You might want to replace http by https in package-lock.json though (as this will flip again at some point in the future).

**Comment by kjetilk** [comment]
I fixed the HTTPS URLs. Will merge if Travis goes green.

**Comment by RubenVerborgh** [comment]
Let's maybe wait for @justinwb to rule out PoPToken issues.

**Comment by kjetilk** [comment]
Ah, right, will do.

**Comment by kjetilk** [comment]
OK, great! @justinwb , will you merge and release 4.1.2?

**Pull request merged**
