### PR TITLE
Add temporary cache in lib/acl-checker.js

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Cache ACL documents and profiles of owners therein for 5 minutes.
Brings the test I did in https://github.com/solid/node-solid-server/issues/1443#issuecomment-675928820 down from 1 minute to 1 second.

**Comment by angelo-v** [comment]
That means, if the cache is not hit, it still takes 5 minutes?

**Comment by michielbdejong** [comment]
> That means, if the cache is not hit, it still takes 5 minutes?

No, if the cache is not hit, it will still fetch the document only once instead of 18 times, so it will still be something like 18 times faster.
If the cache is hit it will be up to 1000 times faster, depending on the ratio between CPU and network speed.

**Comment by michielbdejong** [comment]
> where to declare this server-wide variable.

Yes, good question. It doesn't need to be a singleton though, it doesn't matter if it exists twice, once per execution thread, or even once per http request, just that the less unique it is, the less effective it is. Having it as an in-memory global in the lib/acl-checker.js file feels ok to me now, we can always move it around if our insights change.

> Looks good to me. Lots of other cache strategies are possible, but let's put this in now to get over the performance problem we have now.

Thanks!

**Pull request merged**
