### PR TITLE
Fix/#1171

### PR DESCRIPTION
**Pull request by jaxoncreed**
Fix for issue #1171. Caused by the fix for issue #1120.

### CODE REVIEW

**Comment by michielbdejong** [comment]
I'm trying to decipher what this code did and what you changed. It looks like the decision about whether or not to return index.html is made through many steps, looking at https://github.com/solid/node-solid-server/blob/5e0748ec776b2ebdc495c7fca1a0ac1f9d41b37c/lib/resource-mapper.js:

* searchIndex, a boolean that indicates whether we should try to serve index.html if the requests ends in a slash.
* isIndex, a boolean that indicates whether the URL actually does end in a slash first made on line #L48 (which basically says, if a URL ends in / then isIndex is true).
* createIfNotExists check (don't fully understand that yet)
* this._indexContentType check (don't fully understand that yet)
* Line 104 checks if an index.html file actually exists (note that this question is irrelevant if the http request wants a Turtle response)
* Lines https://github.com/solid/node-solid-server/blob/5e0748ec776b2ebdc495c7fca1a0ac1f9d41b37c/lib/resource-mapper.js#L74-L80 then possibly reverse the previous decision to server index.html, based on the contentType header.

We cannot touch this code without refactoring that decision tree. I would propose to replace it with the following:
* the comment on line https://github.com/solid/node-solid-server/blob/5e0748ec776b2ebdc495c7fca1a0ac1f9d41b37c/lib/resource-mapper.js#L45 to say "Under the following conditions, a trailing `/` in the URL will be interpreted as `/index.html`:
  * the URL ends in a /
  * the searchIndex option is true (which is the default)
  * the content-type header of the request indicates that text/html is prefered over text/turtle
This means that a request for a URL that ends in a / may for instance return a 404 even if the container does exist."

PS: looks to me like the `searchIndex &&` on line https://github.com/solid/node-solid-server/blob/5e0748ec776b2ebdc495c7fca1a0ac1f9d41b37c/lib/resource-mapper.js#L62 should be removed, the decision to add a dollar extension should not be conditional on searchIndex being set to true, right?

**Comment by jaxoncreed** [comment]
I think you're right that the way I fixed the bug was incorrect and I should instead do it with the flags rather than reversing it at the end.

I am unsure that using a trailing "/" to determine if you should serve an index.html correctly aligns with the specs. https://github.com/solid/solid-spec/blob/master/api-rest.md#reading-resources It's clearly stated that if a content-type header is not provided the result should always be in text/turtle

**Comment by michielbdejong** [comment]
ah ok, but then `if isIndex is true, and the URL ends in a slash, and the content-type header of the request indicates that text/html is preferred over text/turtle, fullPath += this._indexFilename` is all we need, right?

**Comment by jaxoncreed** [comment]
In general, this code is pretty messy, but after looking around a bit, I determined that this is the best place to determine whether or not to send html based on the accept header

**Comment by michielbdejong** [comment]
Will have a look tomorrow!

**Comment by michielbdejong** [comment]
Thanks for moving the fix to a better location, the next person touching this code will love you for that! :)

**Comment by jaxoncreed** [comment]
Okay, the last solution had some major problems. This one is less clean, but given the way the code is structured, this is the proper way to do it.

**Pull request merged**
