### PR TITLE
Remove solid:inbox.

### PR DESCRIPTION
**Pull request by RubenVerborgh**
https://github.com/solid/solid-spec/issues/108

### CODE REVIEW

**Comment by kjetilk** [comment]
This is something that should probably go into the `v5.0.0` branch?

**Comment by RubenVerborgh** [comment]
@kjetilk Good pointt.

**Comment by melvincarvalho** [comment]
Just FYI: it's been on my todo list for ages, to add solid : inbox back to the vocabulary only.

It was removed by mistake, before we had a process of pull requests and review.

**Comment by csarven** [comment]
It wasn't removed by mistake, `ldp:inbox` replaces it. LDN standardises the notification system.

**Comment by melvincarvalho** [comment]
@csarven thanks for sharing your view.  However, this is a discussion for the vocab repo.

**Comment by RubenVerborgh** [comment]
As discusses in https://github.com/solid/vocab/issue/31 and https://github.com/solid/vocab/pull/33, it's ldp:inbox now. Rebasing and merging.

**Pull request merged**
