### PR TITLE
Remove old /logout bindings - PR v2

### PR DESCRIPTION
**Pull request by cblakeley**
Replaces https://github.com/solid/node-solid-server/pull/857

This patch is the original patch https://github.com/solid/node-solid-server/pull/857/commits/834aebedfd6a4299e520bd490d6db520196e7c4a for https://github.com/solid/node-solid-server/pull/857 recreated on top of release/v5.0.0 with a prior merge conflict resolved.

### CODE REVIEW

**Comment by kjetilk** [comment]
Mmm, I don't know... As you can see, this pulled in a lot of stuff into the diff, so it seems like a rebase that wasn't quite successful. IIRC, it was just a handful of pretty trivial changes... So, I would prefer if you could try again. We're very tight on time for 5.0.0, so any help is greatly appreciated.

**Comment by kidehen** [comment]
@kjetilk ,

What is the problem now? 

/cc @cblakeley @dmitrizagidulin  @RubenVerborgh

**Comment by melvincarvalho** [comment]
> Looks good to me!

@kjetilk just clarifying, is this OK to merge?

**Comment by kidehen** [comment]
@melvincarvalho ,

Please merge.

**Comment by melvincarvalho** [comment]
@kjetilk 

I had a request from @kidehen that there is some urgency to merge this (and I know you've been unwell).  So given the last comment, and all checks passing, I'm going to go ahead and do that.

**Comment by kjetilk** [comment]
Thanks, @melvincarvalho ! I was going to do it before the 5.0.0 release anyway, just hadn't gotten around to it.

**Pull request merged**
