### PR TITLE
Remove old /logout bindings

### PR DESCRIPTION
**Pull request by cblakeley**
This PR relates to:

  * https://github.com/solid/oidc-op/issues/10#issuecomment-426233886
  * https://github.com/solid/oidc-op/issues/10#issuecomment-426602431

It makes the Solid OP's /logout endpoint invoke RPInitiatedLogoutRequest#handle instead of LogoutRequest#handle. See also: https://github.com/solid/oidc-op/pull/11

### CODE REVIEW

**Comment by cblakeley** [comment]
@RubenVerborgh This PR depends on https://github.com/solid/oidc-op/pull/11 which @dmitrizagidulin is reviewing.

The POST and GET bindings of LogoutRequest#handle (logout v1) to /logout were removed in this PR because they were masking the binding of RPInitiatedLogoutRequest#handle (logout v2) to /logout (https://github.com/solid/node-solid-server/blob/834aebedfd6a4299e520bd490d6db520196e7c4a/lib/api/authn/webid-oidc.js#L108). But, https://github.com/solid/oidc-op/pull/11 is also required to fix issues in RPInitiatedLogoutRequest.

I've tested these changes locally, but I need feedback and assistance from @dmitrizagidulin before these 2 PRs can be moved forward.

**Comment by RubenVerborgh** [comment]
Thanks for clarifying. Then I'm putting this on hold until we hear from @dmitrizagidulin.

**Comment by kjetilk** [comment]
And please rebase on `develop` or `release/v5.0.0` as appropriate.

**Comment by justinwb** [comment]
@kidehen waiting on feedback from @dmitrizagidulin per @kjetilk and @RubenVerborgh's notes above

**Comment by kjetilk** [comment]
yeah, that, and a rebase. :-) Is this a semver minor or major? It seems to change some behavior substantially, doesn't it?

**Comment by cblakeley** [comment]
This PR depends on solid/oidc-op#11

**Comment by RubenVerborgh** [comment]
Blocked by https://github.com/solid/oidc-op/pull/11.

**Comment by dmitrizagidulin** [comment]
👍 , @cblakeley if you can rebase it and resolve the conflict, this is all set.

**Comment by kjetilk** [comment]
Yup, ready to merge when the rebase and conflict is resolved. 

Also, please set the version dep of oidc-op to 0.4.2 while you're at it :-)

**Comment by kjetilk** [comment]
Wasn't this needed anymore, @cblakeley ?

**Comment by cblakeley** [comment]
@kjetilk: I deleted the branch behind this PR and created a new branch/PR https://github.com/solid/node-solid-server/pull/957
containing one patch https://github.com/OpenLinkSoftware/node-solid-server/commit/1341d3571fc63d5d3940ebc4926ab1dba3407c66. It is the original patch (https://github.com/solid/node-solid-server/pull/857/commits/834aebedfd6a4299e520bd490d6db520196e7c4a) on top of release/v5.0.0 with the merge conflict resolved. 

I wasn't able to rebase the original patch and resolve the conflict without recreating the branch. Sorry if this wasn't the right approach.

**Pull request closed without merging**
