### PR TITLE
Fix/#1120

### PR DESCRIPTION
**Pull request by jaxoncreed**
#1120 Root now returns text/turtle when requested

### CODE REVIEW

**Comment by jaxoncreed** [comment]
There are still some edge case problems

**Comment by jaxoncreed** [comment]
Okay good to go now!

**Comment by jaxoncreed** [comment]
@kjetilk I'm going to wait until a successful build of this finishes. Travis CI has apparently been having trouble today, so builds aren't going through

**Comment by michielbdejong** [comment]
Sometimes one in four Travis builds fails. You should be able to log in with your github credentials and click 'restart job' (I just did for this one)

**Comment by gobengo** [comment]
Who is most qualified and experienced to do a root cause analysis on why Travis fails 25% of the time?

**Comment by michielbdejong** [comment]
Re Travis stability, contributions very welcome!

**Comment by gobengo** [comment]
@melvincarvalho It sounds like maybe you're referring to #1119 ?
i.e. the issue might not be specific to Travis? Do you agree? I will comment there.

**Comment by michielbdejong** [comment]
Follow-up re Travis builds failing is in https://github.com/solid/node-solid-server/issues/1119

**Pull request merged**
