### PR TITLE
Adding an extra password field to require users to repeat passwords

### PR DESCRIPTION
**Pull request by megoth**
This is a fix for #822 

Handles backend validation and adds a scripts that validates on frontend as well.

### CODE REVIEW

**Comment by he8us** [comment]
Hello @megoth,
Do you want me to fix the conflicts and check for the stylings of the passwords fields?

**Comment by megoth** [comment]
> Hello @megoth,
> Do you want me to fix the conflicts and check for the stylings of the passwords fields?

Yes, that would be lovely ^_^

> BTW, if we have a repeat password, I think we should remove the "Show password" checkbox.

If anything it might be a bit annoying when you're tabbing through the fields. Let's remove it ^_^

**Comment by he8us** [comment]
It might be a good idea to review and merge #845 before update, so I can uniformise the code

**Comment by megoth** [comment]
Waiting on #845 to be merged into develop (if approved by @kjetilk )

**Comment by he8us** [comment]
@megoth I can't write on the `feature/password-confirm` branch so I imported this branch to my fork, squashed your commits, aligned with develop, fix the conflicts and put my modifications.

When #845 will be merged I'll add a visual feedback on password strength then propose a PR.

**Comment by megoth** [comment]
@he8us great! Thanks for the patience, I forgot about #845 in the midst of all the issues coming in and trying to get an overview of everything =P

**Comment by he8us** [comment]
No problems, I know what this is when you have issues continuously coming ;)

**Comment by kjetilk** [comment]
I just merged #845 , so please go ahead! :-)

**Comment by kjetilk** [comment]
This can be closed, since it was fixed in #859 , right? Please reopen if not.

**Pull request closed without merging**
