### PR TITLE
Removing externalWebId from account creation form

### PR DESCRIPTION
**Pull request by megoth**
Partially solves https://github.com/solid/node-solid-server/issues/1267 - need to implement an API that allows users to configure their externalWebID elsewhere.

We'll discuss this with rest of the team tomorrow. Might discard this PR until we have an API and interface that allows for editing externalWebID.

### CODE REVIEW

**Comment by timbl** [comment]
An alternative to removing it completely would be maybe three things
1-  Hiding it behind an "advanced" section button
2- Explaining exactly what the option is: You have an existing id, and now you just want some more storage for it
3- instead of getting them to type the webid, get them to log in adn grab the webid.  That will save mistypings and misunderstandings

**Comment by timbl** [comment]
The siyte admins also  might not want to enable hosting of pods for existing users.

**Comment by megoth** [comment]
Reg "2- Explaining exactly what the option is: You have an existing id, and now you just want some more storage for it"

This has proven not to work - people simply scan the fields and ignore descriptions.

**Comment by timbl** [comment]
"This has proven not to work"  I don't remember ever seeing a server with a complete explanation.  Is there one?   We have to do ALL three things by the way. 
Are you saying users will never ever understand the concept of having  new pod for their old id, no matter what we write ?  Can you point to the explantion which was given and did not work?

**Comment by megoth** [comment]
Sorry, I should've been more specific; I've been working with forms in my previous work, and all practice shows that many, if not most, people will ignore descriptions as part of a field in a form.

Opt 1 and 3 that you mentioned are things we could try though. I think I'll try opt 1 in a sep branch tomorrow.

**Comment by michielbdejong** [comment]
Can this be closed in favour of #1273?

**Comment by megoth** [comment]
@michielbdejong Yes, I think we'll be going for https://github.com/solid/node-solid-server/pull/1273 instead.

Closing this PR, but might reopen it later in case @timbl disagrees.

**Pull request closed without merging**
