### PR TITLE
Normalize paths for Windows (forward slashes)

### PR DESCRIPTION
**Pull request by highlevellogic**
Normalize paths for Windows (forward slashes)
With these changes, the data browser seems to work well on Windows.
This PR replaces #1499 Normalize rootPath for Windows (forward slashes) 
Related to issues #1534, #1490

My apologies if needed. I realize that testing is done on Linux.
I really intend to work more on tools and applications.
Stuck using Windows at the moment. 

This PR includes the fix from #1499 .. which normalized (to forward slashes) _rootPath on line 33.

Old line 33
this._rootPath = this._removeTrailingSlash(rootPath)

New line 33
this._rootPath = this._removeTrailingSlash(rootPath).replace(/\\/g, '/')

This PR includes one more fix by substituting (on line 87) '/' in place of pathUtil.sep

Old line 87
pathname.split(pathUtil.sep).map((component) => encodeURIComponent(component)).join('/')

New Line 87
pathname.split('/').map((component) => encodeURIComponent(component)).join('/')

### CODE REVIEW

**Comment by bourgeoa** [comment]
@michielbdejong @jaxoncreed 
This PR make the NSS server running under Windows. I created my on pod on @highlevellogic server https://solid.hll.nu:7443
What is the best to use for this PR to resourceMapper.js : 
- replace \ with / 
- or use the node.js path.sep

**Comment by highlevellogic** [comment]
My view from working on Windows fixes these past few weeks is to explicitly use /.
I don't think path.sep should be used ... it just causes confusion.
Solid needs to put things in standard URI form quite a bit.
When reading and writing, Node automatically adapts to the OS.
When hard-coding any path in Node, I use forward slashes.

**Comment by highlevellogic** [comment]
I see that this is not failing on the 10x Ubuntu build, but I don't understand why. It's just a .replace with a small bit of regex. Is resourceMapper (without these changes) generally failing for 10x too?

**Comment by bourgeoa** [comment]
Your test failed on standard checks
```
standard: Use JavaScript Standard Style (https://standardjs.com)
  /home/runner/work/node-solid-server/node-solid-server/lib/resource-mapper.js:9:7: 'pathUtil' is assigned a value but never used.
```

**Comment by highlevellogic** [comment]
const pathUtil = require('path')

No other reference in the file. This PR doesn't change it.

**Comment by bourgeoa** [comment]
If you click on the `files changed` button you shall see that `pathutil` is not used anymore

**Comment by highlevellogic** [comment]
Not getting that from clicking on files changed. Instead getting: 

  overrideTypes = { acl: 'text/turtle', meta: 'text/turtle' }
  }) {
    this._rootUrl = this._removeTrailingSlash(rootUrl)
    this._rootPath = this._removeTrailingSlash(rootPath)
    this._rootPath = this._removeTrailingSlash(rootPath).replace(/\\/g, '/')
    this._includeHost = includeHost
    this._readdir = readdir
    this._defaultContentType = defaultContentType
@@ -84,7 +84,7 @@ class ResourceMapper {
    // Determine the URL by chopping off everything after the dollar sign
    const pathname = this._removeDollarExtension(path)
    const url = `${this.resolveUrl(hostname)}${
      pathname.split(pathUtil.sep).map((component) => encodeURIComponent(component)).join('/')
      pathname.split('/').map((component) => encodeURIComponent(component)).join('/')
    }`
    return { url, contentType: this._getContentTypeFromExtension(path) }
  }

**Comment by highlevellogic** [comment]
I still don't see what this would have to do with Ubutu version.

**Comment by bourgeoa** [comment]
Ubuntu versions are running in parallel. The first that encounters an error make the other to stop running.
Ubuntu 12 and 14 do not succeed. They do stop

**Comment by bourgeoa** [comment]
You did not use the `files changed` button that is on the right bellow the PR title. This button gives you a cumulative of all commits.

**Comment by highlevellogic** [comment]
I can even do a page search for "files changed" and yes, it's the option below the PR title, to the right of Conversation, Commits, and Checks. Not matter what it says, this seems out of context. Was there a problem with the code in earlier versions of Ubuntu? That have nothing to do with my proposed changes? Seriously - I have no problem at all with also deleting that line of useless code. I'll be involved with it if needed - but it's confusing - why would I need to be involved with it?

**Comment by bourgeoa** [comment]
I do not understand your problem.
- The tests run on the cumulative commits of the PR 
- The tests begin with a formal checking of the code.
- `pathutil is not used`. The tests stop

**Comment by highlevellogic** [comment]
> 
> 
> I do not understand your problem.
> 
>     * The tests run on the cumulative commits of the PR
> 
>     * The tests begin with a formal checking of the code.
> 
>     * `pathutil is not used`. The tests stop

We can start with why is that my problem and if it is (or I can help fix it ....), what should I do about it. It is unrelated and irrelevant to the fixes in the PR. But anyway ... what's needed?

**Comment by TallTed** [comment]
@highlevellogic -- 

Here's a thought...

Try commenting out the line that seems to be causing the error, i.e. --

     9  const pathUtil = require('path')

-- and add a note that your change to this other line --

    87  pathname.split(pathUtil.sep).map((component) => encodeURIComponent(component)).join('/')

-- took out the only other reference to `pathUtil` in this file, apparently resulting in the build fails on (at least) Ubuntu --

    87  pathname.split('/').map((component) => encodeURIComponent(component)).join('/')

Then see if the build is still broken.  If not, then take the next step, and delete the now-commented line 9.  If still broken, then it is clearly beyond your control.

**Comment by highlevellogic** [comment]
Thank you. I'm just pushing hard to get some other software finished. I'll fix this.

**Comment by highlevellogic** [comment]
A lot of time has passed on this one and it seems kind-of like a no-brainer to merge.
If we're playing by Inrupt rules, then anyone with sufficient authorization can do it without group approval.
There are other problems for running on Windows, but I won't work further on them if the fixes aren't going to be merged.
May I suggest, that among other considerations, it could be of value to be first to market on all platforms.

**Review by bourgeoa — APPROVED** [review]

**Pull request merged**
