### PR TITLE
Delete .acl file for resource when resource is deleted

### PR DESCRIPTION
**Pull request by fabiancook**
Delete .acl file for resource when resource is deleted, also ignore any acl or meta files in directory when deleting. 

I had troubles with some TLS not passing, locally I skipped them. I also had issues with the quota tests, its like the signature of ldp changed at some point, so I redid the test so it tests correctly.

### CODE REVIEW

**Comment by fabiancook** [comment]
Fixes https://github.com/solid/node-solid-server/issues/1179

**Comment by fabiancook** [comment]
I'll rebase in & re-push once the other failing tests are corrected.

**Comment by jaxoncreed** [comment]
@fabiancook There seems to be a problem with quotas causing the test to fail. Would you mind looking at that?

**Comment by fabiancook** [comment]
The quota tests look like they've never worked, I don't have the bandwidth to debug those errors at this time.

**Comment by kjetilk** [comment]
I think they did work. But I'm unsure why this should need to touch those?

**Comment by jaxoncreed** [comment]
Yeah. I checked yesterday. The current master has 100% passing tests.

**Comment by fabiancook** [comment]
Perfect, I'll rebase to current master

**Comment by fabiancook** [comment]
Can someone help me with the quota issue? A pointer would be helpful. 

The original quota tests never would have run, either, which is why I added a new one.

**Comment by fabiancook** [comment]
The only thing I'm wondering now is if I should change this line here so only `acl` files are checked for, where `meta` files are only ignored if it is the containers `meta` file:

https://github.com/solid/node-solid-server/pull/1180/commits/4e268e3bb2f1731da190343bf1f9db01cdb0a872#diff-4b9b8e50857ade6dd5db969387fe5f20R415 

This would depend on this issue: https://github.com/solid/solid-spec/issues/172

**Comment by RubenVerborgh** [comment]
See https://github.com/solid/solid-spec/issues/157 as well

**Comment by jaxoncreed** [comment]
So I think we're good to go to merge this then.

**Comment by RubenVerborgh** [comment]
> So I think we're good to go to merge this then.

I'm not sure, do we have consensus that this is the desired behavior?
There are security consequences when this happens.

Also, given that we're considering #190, there are other means of discovering and deleting the ACL file.

**Comment by kjetilk** [comment]
Technically, it looks good to me, but I think we don't yet have consensus on whether this is what we want.

**Comment by jaxoncreed** [comment]
It sounds like @RubenVerborgh 's two suggestions should be fixed first.

**Comment by RubenVerborgh** [comment]
Also need to consider security, in https://github.com/solid/solid-spec/issues/196

**Comment by michielbdejong** [comment]
Continued in #1415.

**Pull request closed without merging**
