### PR TITLE
Add Vary: Accept header

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Addresses #636

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
I'll check in a bit.

**Comment by RubenVerborgh** [comment]
Debug log for the above case is 

```
solid:server Error page because of: { Error: Could not verify Web ID from token claims
    at oidc.webIdFromClaims.then.catch.err (/Users/ruben/Documents/UGent/MIT/Solid/node-solid-server/lib/api/authn/webid-oidc.js:48:21)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  statusCode: 401,
  cause: Error: Preferred provider for Web ID https://ruben.verborgh.org/profile/#me does not match token issuer https://localhost:8443
    at discoverProviderFor.then.preferredProvider (/Users/ruben/Documents/UGent/MIT/Solid/oidc-auth-manager/src/oidc-manager.js:388:15)
    at process._tickCallback (internal/process/next_tick.js:178:7) } +8s
```

**Comment by dmitrizagidulin** [comment]
@kjetilk no worries there. the CORS lib automatically adds it for us.

**Comment by RubenVerborgh** [comment]
> the CORS lib automatically adds it for us.

Except that it doesn't in at least one case, see above :wink:

**Comment by dmitrizagidulin** [comment]
Oh I see. Hmmm. Lets try it?

**Comment by dmitrizagidulin** [comment]
Er, wait a minute.

**Comment by dmitrizagidulin** [comment]
No, I think that behavior is correct. The error log above has no Origin because it’s a server-side fetch, not from a browser

**Comment by RubenVerborgh** [comment]
That doesn't matter; `Vary` still needs to be correct for proxies etc.

**Comment by dmitrizagidulin** [comment]
Ah, ok. Well, lets set it ourselves then

**Comment by kjetilk** [comment]
You'd think that a HTTP library somewhere would prevent duplicates from being sent to the client...? Should we just set it and see what happens?

**Comment by RubenVerborgh** [comment]
Sure. A duplicate wouldn't be _that_ bad.

**Comment by kjetilk** [comment]
I can't see more than one ```Vary``` header, and no duplicated ```Origin```. 

If there are any cases where you would expect a duplicate, could you please check, @RubenVerborgh ?

**Pull request merged**
